set-option -sa terminal-overrides ",alacritty:RGB,xterm*:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'ofirgall/tmux-window-name' 
set -g @plugin 'git@github.com:mmikotajewski-vivlio/claude_tmux_blink.git'
set -g @claude-await-simulate-blink on

# Make navigation between windows easier
bind -n M-H previous-window
bind -n M-L next-window

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

# Use the mouse in tmux
set -g mouse on

# Start indexing panes and windows at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-V send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# TODO : Clean me
set-option -g default-shell /home/maxime/opt/fish/fish

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Change this one line to switch theme. The other flavours sit next to it:
# tokyonight_storm, tokyonight_moon, tokyonight_day.
source-file ~/.config/tmux/themes/tokyonight_night.tmux
